/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as PrayerJournalingRouteImport } from './routes/prayer-journaling'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HeartNotesRouteImport } from './routes/heart-notes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DailyDevotionalRouteImport } from './routes/daily-devotional'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChristianJournalingRouteImport } from './routes/christian-journaling'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerJournalingRoute = PrayerJournalingRouteImport.update({
  id: '/prayer-journaling',
  path: '/prayer-journaling',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartNotesRoute = HeartNotesRouteImport.update({
  id: '/heart-notes',
  path: '/heart-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyDevotionalRoute = DailyDevotionalRouteImport.update({
  id: '/daily-devotional',
  path: '/daily-devotional',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChristianJournalingRoute = ChristianJournalingRouteImport.update({
  id: '/christian-journaling',
  path: '/christian-journaling',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faq': typeof FaqRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faq': typeof FaqRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faq': typeof FaqRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faq'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faq'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faq'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChristianJournalingRoute: typeof ChristianJournalingRoute
  ContactRoute: typeof ContactRoute
  DailyDevotionalRoute: typeof DailyDevotionalRoute
  FaqRoute: typeof FaqRoute
  HeartNotesRoute: typeof HeartNotesRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrayerJournalingRoute: typeof PrayerJournalingRoute
  PrayersRoute: typeof PrayersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-journaling': {
      id: '/prayer-journaling'
      path: '/prayer-journaling'
      fullPath: '/prayer-journaling'
      preLoaderRoute: typeof PrayerJournalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heart-notes': {
      id: '/heart-notes'
      path: '/heart-notes'
      fullPath: '/heart-notes'
      preLoaderRoute: typeof HeartNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-devotional': {
      id: '/daily-devotional'
      path: '/daily-devotional'
      fullPath: '/daily-devotional'
      preLoaderRoute: typeof DailyDevotionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christian-journaling': {
      id: '/christian-journaling'
      path: '/christian-journaling'
      fullPath: '/christian-journaling'
      preLoaderRoute: typeof ChristianJournalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChristianJournalingRoute: ChristianJournalingRoute,
  ContactRoute: ContactRoute,
  DailyDevotionalRoute: DailyDevotionalRoute,
  FaqRoute: FaqRoute,
  HeartNotesRoute: HeartNotesRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrayerJournalingRoute: PrayerJournalingRoute,
  PrayersRoute: PrayersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
