/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuietTimeAppRouteImport } from './routes/quiet-time-app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as PrayerJournalingRouteImport } from './routes/prayer-journaling'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HeartNotesRouteImport } from './routes/heart-notes'
import { Route as FreePrayerToolkitRouteImport } from './routes/free-prayer-toolkit'
import { Route as FastingGuideRouteImport } from './routes/fasting-guide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FaithHabitTrackerRouteImport } from './routes/faith-habit-tracker'
import { Route as DailyDevotionalRouteImport } from './routes/daily-devotional'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChristianJournalingRouteImport } from './routes/christian-journaling'
import { Route as AnsweredPrayerTrackerRouteImport } from './routes/answered-prayer-tracker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R7DayPrayerJournalRouteImport } from './routes/7-day-prayer-journal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as DevotionalIndexRouteImport } from './routes/devotional.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as DevotionalDateRouteImport } from './routes/devotional.$date'
import { Route as BlogBuildingGracenotesDailyRouteImport } from './routes/blog.building-gracenotes-daily'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuietTimeAppRoute = QuietTimeAppRouteImport.update({
  id: '/quiet-time-app',
  path: '/quiet-time-app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerJournalingRoute = PrayerJournalingRouteImport.update({
  id: '/prayer-journaling',
  path: '/prayer-journaling',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartNotesRoute = HeartNotesRouteImport.update({
  id: '/heart-notes',
  path: '/heart-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePrayerToolkitRoute = FreePrayerToolkitRouteImport.update({
  id: '/free-prayer-toolkit',
  path: '/free-prayer-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const FastingGuideRoute = FastingGuideRouteImport.update({
  id: '/fasting-guide',
  path: '/fasting-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithHabitTrackerRoute = FaithHabitTrackerRouteImport.update({
  id: '/faith-habit-tracker',
  path: '/faith-habit-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyDevotionalRoute = DailyDevotionalRouteImport.update({
  id: '/daily-devotional',
  path: '/daily-devotional',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChristianJournalingRoute = ChristianJournalingRouteImport.update({
  id: '/christian-journaling',
  path: '/christian-journaling',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsweredPrayerTrackerRoute = AnsweredPrayerTrackerRouteImport.update({
  id: '/answered-prayer-tracker',
  path: '/answered-prayer-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R7DayPrayerJournalRoute = R7DayPrayerJournalRouteImport.update({
  id: '/7-day-prayer-journal',
  path: '/7-day-prayer-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalIndexRoute = DevotionalIndexRouteImport.update({
  id: '/devotional/',
  path: '/devotional/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalDateRoute = DevotionalDateRouteImport.update({
  id: '/devotional/$date',
  path: '/devotional/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBuildingGracenotesDailyRoute =
  BlogBuildingGracenotesDailyRouteImport.update({
    id: '/blog/building-gracenotes-daily',
    path: '/blog/building-gracenotes-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/7-day-prayer-journal': typeof R7DayPrayerJournalRoute
  '/about': typeof AboutRoute
  '/answered-prayer-tracker': typeof AnsweredPrayerTrackerRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faith-habit-tracker': typeof FaithHabitTrackerRoute
  '/faq': typeof FaqRoute
  '/fasting-guide': typeof FastingGuideRoute
  '/free-prayer-toolkit': typeof FreePrayerToolkitRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/quiet-time-app': typeof QuietTimeAppRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/building-gracenotes-daily': typeof BlogBuildingGracenotesDailyRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/devotional/': typeof DevotionalIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/7-day-prayer-journal': typeof R7DayPrayerJournalRoute
  '/about': typeof AboutRoute
  '/answered-prayer-tracker': typeof AnsweredPrayerTrackerRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faith-habit-tracker': typeof FaithHabitTrackerRoute
  '/faq': typeof FaqRoute
  '/fasting-guide': typeof FastingGuideRoute
  '/free-prayer-toolkit': typeof FreePrayerToolkitRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/quiet-time-app': typeof QuietTimeAppRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/building-gracenotes-daily': typeof BlogBuildingGracenotesDailyRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/devotional': typeof DevotionalIndexRoute
  '/library': typeof LibraryIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/7-day-prayer-journal': typeof R7DayPrayerJournalRoute
  '/about': typeof AboutRoute
  '/answered-prayer-tracker': typeof AnsweredPrayerTrackerRoute
  '/christian-journaling': typeof ChristianJournalingRoute
  '/contact': typeof ContactRoute
  '/daily-devotional': typeof DailyDevotionalRoute
  '/faith-habit-tracker': typeof FaithHabitTrackerRoute
  '/faq': typeof FaqRoute
  '/fasting-guide': typeof FastingGuideRoute
  '/free-prayer-toolkit': typeof FreePrayerToolkitRoute
  '/heart-notes': typeof HeartNotesRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer-journaling': typeof PrayerJournalingRoute
  '/prayers': typeof PrayersRoute
  '/privacy': typeof PrivacyRoute
  '/quiet-time-app': typeof QuietTimeAppRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/building-gracenotes-daily': typeof BlogBuildingGracenotesDailyRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/devotional/': typeof DevotionalIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/7-day-prayer-journal'
    | '/about'
    | '/answered-prayer-tracker'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faith-habit-tracker'
    | '/faq'
    | '/fasting-guide'
    | '/free-prayer-toolkit'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/quiet-time-app'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/blog/building-gracenotes-daily'
    | '/devotional/$date'
    | '/library/$slug'
    | '/devotional/'
    | '/library/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/7-day-prayer-journal'
    | '/about'
    | '/answered-prayer-tracker'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faith-habit-tracker'
    | '/faq'
    | '/fasting-guide'
    | '/free-prayer-toolkit'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/quiet-time-app'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/blog/building-gracenotes-daily'
    | '/devotional/$date'
    | '/library/$slug'
    | '/devotional'
    | '/library'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/7-day-prayer-journal'
    | '/about'
    | '/answered-prayer-tracker'
    | '/christian-journaling'
    | '/contact'
    | '/daily-devotional'
    | '/faith-habit-tracker'
    | '/faq'
    | '/fasting-guide'
    | '/free-prayer-toolkit'
    | '/heart-notes'
    | '/home'
    | '/journey'
    | '/listen'
    | '/login'
    | '/onboarding'
    | '/prayer-journaling'
    | '/prayers'
    | '/privacy'
    | '/quiet-time-app'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/blog/building-gracenotes-daily'
    | '/devotional/$date'
    | '/library/$slug'
    | '/devotional/'
    | '/library/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R7DayPrayerJournalRoute: typeof R7DayPrayerJournalRoute
  AboutRoute: typeof AboutRoute
  AnsweredPrayerTrackerRoute: typeof AnsweredPrayerTrackerRoute
  ChristianJournalingRoute: typeof ChristianJournalingRoute
  ContactRoute: typeof ContactRoute
  DailyDevotionalRoute: typeof DailyDevotionalRoute
  FaithHabitTrackerRoute: typeof FaithHabitTrackerRoute
  FaqRoute: typeof FaqRoute
  FastingGuideRoute: typeof FastingGuideRoute
  FreePrayerToolkitRoute: typeof FreePrayerToolkitRoute
  HeartNotesRoute: typeof HeartNotesRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrayerJournalingRoute: typeof PrayerJournalingRoute
  PrayersRoute: typeof PrayersRoute
  PrivacyRoute: typeof PrivacyRoute
  QuietTimeAppRoute: typeof QuietTimeAppRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogBuildingGracenotesDailyRoute: typeof BlogBuildingGracenotesDailyRoute
  DevotionalDateRoute: typeof DevotionalDateRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  DevotionalIndexRoute: typeof DevotionalIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiet-time-app': {
      id: '/quiet-time-app'
      path: '/quiet-time-app'
      fullPath: '/quiet-time-app'
      preLoaderRoute: typeof QuietTimeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-journaling': {
      id: '/prayer-journaling'
      path: '/prayer-journaling'
      fullPath: '/prayer-journaling'
      preLoaderRoute: typeof PrayerJournalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heart-notes': {
      id: '/heart-notes'
      path: '/heart-notes'
      fullPath: '/heart-notes'
      preLoaderRoute: typeof HeartNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-prayer-toolkit': {
      id: '/free-prayer-toolkit'
      path: '/free-prayer-toolkit'
      fullPath: '/free-prayer-toolkit'
      preLoaderRoute: typeof FreePrayerToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasting-guide': {
      id: '/fasting-guide'
      path: '/fasting-guide'
      fullPath: '/fasting-guide'
      preLoaderRoute: typeof FastingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith-habit-tracker': {
      id: '/faith-habit-tracker'
      path: '/faith-habit-tracker'
      fullPath: '/faith-habit-tracker'
      preLoaderRoute: typeof FaithHabitTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-devotional': {
      id: '/daily-devotional'
      path: '/daily-devotional'
      fullPath: '/daily-devotional'
      preLoaderRoute: typeof DailyDevotionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christian-journaling': {
      id: '/christian-journaling'
      path: '/christian-journaling'
      fullPath: '/christian-journaling'
      preLoaderRoute: typeof ChristianJournalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answered-prayer-tracker': {
      id: '/answered-prayer-tracker'
      path: '/answered-prayer-tracker'
      fullPath: '/answered-prayer-tracker'
      preLoaderRoute: typeof AnsweredPrayerTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7-day-prayer-journal': {
      id: '/7-day-prayer-journal'
      path: '/7-day-prayer-journal'
      fullPath: '/7-day-prayer-journal'
      preLoaderRoute: typeof R7DayPrayerJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional/': {
      id: '/devotional/'
      path: '/devotional'
      fullPath: '/devotional/'
      preLoaderRoute: typeof DevotionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional/$date': {
      id: '/devotional/$date'
      path: '/devotional/$date'
      fullPath: '/devotional/$date'
      preLoaderRoute: typeof DevotionalDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/building-gracenotes-daily': {
      id: '/blog/building-gracenotes-daily'
      path: '/blog/building-gracenotes-daily'
      fullPath: '/blog/building-gracenotes-daily'
      preLoaderRoute: typeof BlogBuildingGracenotesDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R7DayPrayerJournalRoute: R7DayPrayerJournalRoute,
  AboutRoute: AboutRoute,
  AnsweredPrayerTrackerRoute: AnsweredPrayerTrackerRoute,
  ChristianJournalingRoute: ChristianJournalingRoute,
  ContactRoute: ContactRoute,
  DailyDevotionalRoute: DailyDevotionalRoute,
  FaithHabitTrackerRoute: FaithHabitTrackerRoute,
  FaqRoute: FaqRoute,
  FastingGuideRoute: FastingGuideRoute,
  FreePrayerToolkitRoute: FreePrayerToolkitRoute,
  HeartNotesRoute: HeartNotesRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrayerJournalingRoute: PrayerJournalingRoute,
  PrayersRoute: PrayersRoute,
  PrivacyRoute: PrivacyRoute,
  QuietTimeAppRoute: QuietTimeAppRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogBuildingGracenotesDailyRoute: BlogBuildingGracenotesDailyRoute,
  DevotionalDateRoute: DevotionalDateRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  DevotionalIndexRoute: DevotionalIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
